language: haskell
notifications:
  email: false
before_script:
  - cabal configure
  - cabal sdist
  - cd ..
  - tar -xf vault/dist/vault*.tar.gz
  - cd vault*
script:
  - cabal configure --enable-tests && cabal build && cabal test
